version: '3.8'

services:
  # 1. Database Service
  mongodb:
    image: mongo:6.0
    container_name: ticket_craft_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ticket_network

  # 2. Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ticket_craft_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://sample:1234@cluster0.gjfox0w.mongodb.net/event_tickets?appName=Cluster0
      - JWT_SECRET=super_secret_devops_key_123
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - ticket_network

  # 3. Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ticket_craft_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ticket_network

volumes:
  mongo_data:

networks:
  ticket_network:
    driver: bridge